NAME:=game

DEPENDENCIES:= \
	libs/content \

SOURCES:= \
	level_state.cpp \
	world/animations/animation_presenter.cpp \
	world/animations/aspects/update_slide_ceiling_sky_aspect.cpp \
	world/animations/aspects/update_slide_surface_aspect.cpp \
	world/animations/aspects/update_surface_light_aspect.cpp \
	world/animations/aspects/update_surface_material_aspect.cpp \
	world/animations/components/slide_ceiling_sky.cpp \
	world/animations/components/slide_surface.cpp \
	world/animations/components/surface_animation.cpp \
	world/animations/components/surface_light.cpp \
	world/animations/components/surface_material.cpp \
	world/animations/events/stop_animation.cpp \
	world/aspects/actor_controller_aspect.cpp \
	world/aspects/character_controller_aspect.cpp \
	world/aspects/dispatch_class_sound_aspect.cpp \
	world/aspects/item_controller_aspect.cpp \
	world/aspects/puppet_animation_aspect.cpp \
	world/aspects/thing_controller_aspect.cpp \
	world/aspects/weapon_controller_aspect.cpp \
	world/camera/camera_model.cpp \
	world/camera/camera_presenter.cpp \
	world/camera/camera_state.cpp \
	world/camera/current_camera_state.cpp \
	world/components/actor.cpp \
	world/components/character.cpp \
	world/components/class_sounds.cpp \
	world/components/item.cpp \
	world/components/player.cpp \
	world/components/puppet_animations.cpp \
	world/components/thing.cpp \
	world/components/weapon.cpp \
	world/events/animation_marker.cpp \
	world/events/armed_mode_changed.cpp \
	world/events/class_sound.cpp \
	world/events/jumped.cpp \
	world/events/killed.cpp \
	world/events/landed.cpp \
	world/events/standing_material_changed.cpp \
	world/events/taken.cpp \
	world/events/thing_created.cpp \
	world/events/touched_surface.cpp \
	world/events/touched_thing.cpp \
	world/inventory/inventory_model.cpp \
	world/inventory/inventory_presenter.cpp \
	world/keys/key_model.cpp \
	world/keys/key_presenter.cpp \
	world/level_model.cpp \
	world/level_place.cpp \
	world/level_presenter.cpp \
	world/physics/contact.cpp \
	world/physics/object_data.cpp \
	world/physics/physics_presenter.cpp \
	world/physics/query.cpp \
	world/physics/shape.cpp \
	world/scripts/script_model.cpp \
	world/scripts/script_presenter.cpp \
	world/sounds/aspects/sound_aspect.cpp \
	world/sounds/aspects/thing_sound_aspect.cpp \
	world/sounds/components/foley.cpp \
	world/sounds/components/sound.cpp \
	world/sounds/components/stop_when_destroyed.cpp \
	world/sounds/components/thing_sound.cpp \
	world/sounds/components/voice.cpp \
	world/sounds/music.cpp \
	world/sounds/sound_model.cpp \
	world/sounds/sound_presenter.cpp \
	world/surface.cpp \
