NAME:=content

DEPENDENCIES:= \
	libs/base \
	libs/cog \

SOURCES:= \
	assets/animation.cpp \
	assets/bitmap_cel.cpp \
	assets/bitmap.cpp \
	assets/colormap.cpp \
	assets/inventory_bin.cpp \
	assets/inventory.cpp \
	assets/level.cpp \
	assets/material_cel.cpp \
	assets/material.cpp \
	assets/model.cpp \
	assets/puppet.cpp \
	assets/script.cpp \
	assets/sfont.cpp \
	assets/soundclass.cpp \
	assets/sprite.cpp \
	assets/template.cpp \
	loaders/animation_loader.cpp \
	loaders/bitmap_loader.cpp \
	loaders/colormap_loader.cpp \
	loaders/inventory_loader.cpp \
	loaders/level_loader.cpp \
	loaders/material_loader.cpp \
	loaders/model_loader.cpp \
	loaders/puppet_loader.cpp \
	loaders/script_loader.cpp \
	loaders/sfont_loader.cpp \
	loaders/soundclass_loader.cpp \
	loaders/sprite_loader.cpp \
	vfs/container.cpp \
	vfs/episode/entry.cpp \
	vfs/episode/episode.cpp \
	vfs/gob/gob_container.cpp \
	vfs/gob/gob_file.cpp \
	vfs/gob/gob_virtual_file.cpp \
	vfs/virtual_file.cpp \
	vfs/virtual_file_system.cpp \
