#pragma once

#include <string>

namespace gorc {

    enum class keyboard_key {
        unknown = -1,
        a = 0,
        b,
        c,
        d,
        e,
        f,
        g,
        h,
        i,
        j,
        k,
        l,
        m,
        n,
        o,
        p,
        q,
        r,
        s,
        t,
        u,
        v,
        w,
        x,
        y,
        z,
        num0,
        num1,
        num2,
        num3,
        num4,
        num5,
        num6,
        num7,
        num8,
        num9,
        escape,
        left_control,
        left_shift,
        left_alt,
        left_meta,
        right_control,
        right_shift,
        right_alt,
        right_meta,
        menu,
        left_bracket,
        right_bracket,
        semicolon,
        comma,
        period,
        quote,
        slash,
        backslash,
        tilde,
        equal,
        dash,
        space,
        enter,
        backspace,
        tab,
        page_up,
        page_down,
        end,
        home,
        insert,
        del,
        add,
        subtract,
        multiply,
        divide,
        left,
        right,
        up,
        down,
        numpad0,
        numpad1,
        numpad2,
        numpad3,
        numpad4,
        numpad5,
        numpad6,
        numpad7,
        numpad8,
        numpad9,
        f1,
        f2,
        f3,
        f4,
        f5,
        f6,
        f7,
        f8,
        f9,
        f10,
        f11,
        f12,
        f13,
        f14,
        f15,
        pause,

        key_count
    };

    keyboard_key string_to_keyboard_key(std::string const&);
    std::string const &keyboard_key_to_string(keyboard_key);

    class keyboard {
    public:
        virtual ~keyboard();

        virtual bool is_key_down(keyboard_key) const = 0;
    };

}
