#include "keyboard.hpp"
#include <unordered_map>
#include "utility/enum_hash.hpp"

using namespace gorc;

namespace {

    std::unordered_map<std::string, keyboard_key> string_to_keyboard_key_map {
        { "a", keyboard_key::a },
        { "b", keyboard_key::b },
        { "c", keyboard_key::c },
        { "d", keyboard_key::d },
        { "e", keyboard_key::e },
        { "f", keyboard_key::f },
        { "g", keyboard_key::g },
        { "h", keyboard_key::h },
        { "i", keyboard_key::i },
        { "j", keyboard_key::j },
        { "k", keyboard_key::k },
        { "l", keyboard_key::l },
        { "m", keyboard_key::m },
        { "n", keyboard_key::n },
        { "o", keyboard_key::o },
        { "p", keyboard_key::p },
        { "q", keyboard_key::q },
        { "r", keyboard_key::r },
        { "s", keyboard_key::s },
        { "t", keyboard_key::t },
        { "u", keyboard_key::u },
        { "v", keyboard_key::v },
        { "w", keyboard_key::w },
        { "x", keyboard_key::x },
        { "y", keyboard_key::y },
        { "z", keyboard_key::z },
        { "num0", keyboard_key::num0 },
        { "num1", keyboard_key::num1 },
        { "num2", keyboard_key::num2 },
        { "num3", keyboard_key::num3 },
        { "num4", keyboard_key::num4 },
        { "num5", keyboard_key::num5 },
        { "num6", keyboard_key::num6 },
        { "num7", keyboard_key::num7 },
        { "num8", keyboard_key::num8 },
        { "num9", keyboard_key::num9 },
        { "escape", keyboard_key::escape },
        { "left_control", keyboard_key::left_control },
        { "left_shift", keyboard_key::left_shift },
        { "left_alt", keyboard_key::left_alt },
        { "left_meta", keyboard_key::left_meta },
        { "right_control", keyboard_key::right_control },
        { "right_shift", keyboard_key::right_shift },
        { "right_alt", keyboard_key::right_alt },
        { "right_meta", keyboard_key::right_meta },
        { "menu", keyboard_key::menu },
        { "left_bracket", keyboard_key::left_bracket },
        { "right_bracket", keyboard_key::right_bracket },
        { "semicolon", keyboard_key::semicolon },
        { "comma", keyboard_key::comma },
        { "period", keyboard_key::period },
        { "quote", keyboard_key::quote },
        { "slash", keyboard_key::slash },
        { "backslash", keyboard_key::backslash },
        { "tilde", keyboard_key::tilde },
        { "equal", keyboard_key::equal },
        { "dash", keyboard_key::dash },
        { "space", keyboard_key::space },
        { "enter", keyboard_key::enter },
        { "backspace", keyboard_key::backspace },
        { "tab", keyboard_key::tab },
        { "page_up", keyboard_key::page_up },
        { "page_down", keyboard_key::page_down },
        { "end", keyboard_key::end },
        { "home", keyboard_key::home },
        { "insert", keyboard_key::insert },
        { "del", keyboard_key::del },
        { "add", keyboard_key::add },
        { "subtract", keyboard_key::subtract },
        { "multiply", keyboard_key::multiply },
        { "divide", keyboard_key::divide },
        { "left", keyboard_key::left },
        { "right", keyboard_key::right },
        { "up", keyboard_key::up },
        { "down", keyboard_key::down },
        { "numpad0", keyboard_key::numpad0 },
        { "numpad1", keyboard_key::numpad1 },
        { "numpad2", keyboard_key::numpad2 },
        { "numpad3", keyboard_key::numpad3 },
        { "numpad4", keyboard_key::numpad4 },
        { "numpad5", keyboard_key::numpad5 },
        { "numpad6", keyboard_key::numpad6 },
        { "numpad7", keyboard_key::numpad7 },
        { "numpad8", keyboard_key::numpad8 },
        { "numpad9", keyboard_key::numpad9 },
        { "f1", keyboard_key::f1 },
        { "f2", keyboard_key::f2 },
        { "f3", keyboard_key::f3 },
        { "f4", keyboard_key::f4 },
        { "f5", keyboard_key::f5 },
        { "f6", keyboard_key::f6 },
        { "f7", keyboard_key::f7 },
        { "f8", keyboard_key::f8 },
        { "f9", keyboard_key::f9 },
        { "f10", keyboard_key::f10 },
        { "f11", keyboard_key::f11 },
        { "f12", keyboard_key::f12 },
        { "f13", keyboard_key::f13 },
        { "f14", keyboard_key::f14 },
        { "f15", keyboard_key::f15 },
        { "pause", keyboard_key::pause }
    };

    std::unordered_map<keyboard_key, std::string, enum_hash<keyboard_key>>
        keyboard_key_to_string_map {
        { keyboard_key::a, "a" },
        { keyboard_key::b, "b" },
        { keyboard_key::c, "c" },
        { keyboard_key::d, "d" },
        { keyboard_key::e, "e" },
        { keyboard_key::f, "f" },
        { keyboard_key::g, "g" },
        { keyboard_key::h, "h" },
        { keyboard_key::i, "i" },
        { keyboard_key::j, "j" },
        { keyboard_key::k, "k" },
        { keyboard_key::l, "l" },
        { keyboard_key::m, "m" },
        { keyboard_key::n, "n" },
        { keyboard_key::o, "o" },
        { keyboard_key::p, "p" },
        { keyboard_key::q, "q" },
        { keyboard_key::r, "r" },
        { keyboard_key::s, "s" },
        { keyboard_key::t, "t" },
        { keyboard_key::u, "u" },
        { keyboard_key::v, "v" },
        { keyboard_key::w, "w" },
        { keyboard_key::x, "x" },
        { keyboard_key::y, "y" },
        { keyboard_key::z, "z" },
        { keyboard_key::num0, "num0" },
        { keyboard_key::num1, "num1" },
        { keyboard_key::num2, "num2" },
        { keyboard_key::num3, "num3" },
        { keyboard_key::num4, "num4" },
        { keyboard_key::num5, "num5" },
        { keyboard_key::num6, "num6" },
        { keyboard_key::num7, "num7" },
        { keyboard_key::num8, "num8" },
        { keyboard_key::num9, "num9" },
        { keyboard_key::escape, "escape" },
        { keyboard_key::left_control, "left_control" },
        { keyboard_key::left_shift, "left_shift" },
        { keyboard_key::left_alt, "left_alt" },
        { keyboard_key::left_meta, "left_meta" },
        { keyboard_key::right_control, "right_control" },
        { keyboard_key::right_shift, "right_shift" },
        { keyboard_key::right_alt, "right_alt" },
        { keyboard_key::right_meta, "right_meta" },
        { keyboard_key::menu, "menu" },
        { keyboard_key::left_bracket, "left_bracket" },
        { keyboard_key::right_bracket, "right_bracket" },
        { keyboard_key::semicolon, "semicolon" },
        { keyboard_key::comma, "comma" },
        { keyboard_key::period, "period" },
        { keyboard_key::quote, "quote" },
        { keyboard_key::slash, "slash" },
        { keyboard_key::backslash, "backslash" },
        { keyboard_key::tilde, "tilde" },
        { keyboard_key::equal, "equal" },
        { keyboard_key::dash, "dash" },
        { keyboard_key::space, "space" },
        { keyboard_key::enter, "enter" },
        { keyboard_key::backspace, "backspace" },
        { keyboard_key::tab, "tab" },
        { keyboard_key::page_up, "page_up" },
        { keyboard_key::page_down, "page_down" },
        { keyboard_key::end, "end" },
        { keyboard_key::home, "home" },
        { keyboard_key::insert, "insert" },
        { keyboard_key::del, "del" },
        { keyboard_key::add, "add" },
        { keyboard_key::subtract, "subtract" },
        { keyboard_key::multiply, "multiply" },
        { keyboard_key::divide, "divide" },
        { keyboard_key::left, "left" },
        { keyboard_key::right, "right" },
        { keyboard_key::up, "up" },
        { keyboard_key::down, "down" },
        { keyboard_key::numpad0, "numpad0" },
        { keyboard_key::numpad1, "numpad1" },
        { keyboard_key::numpad2, "numpad2" },
        { keyboard_key::numpad3, "numpad3" },
        { keyboard_key::numpad4, "numpad4" },
        { keyboard_key::numpad5, "numpad5" },
        { keyboard_key::numpad6, "numpad6" },
        { keyboard_key::numpad7, "numpad7" },
        { keyboard_key::numpad8, "numpad8" },
        { keyboard_key::numpad9, "numpad9" },
        { keyboard_key::f1, "f1" },
        { keyboard_key::f2, "f2" },
        { keyboard_key::f3, "f3" },
        { keyboard_key::f4, "f4" },
        { keyboard_key::f5, "f5" },
        { keyboard_key::f6, "f6" },
        { keyboard_key::f7, "f7" },
        { keyboard_key::f8, "f8" },
        { keyboard_key::f9, "f9" },
        { keyboard_key::f10, "f10" },
        { keyboard_key::f11, "f11" },
        { keyboard_key::f12, "f12" },
        { keyboard_key::f13, "f13" },
        { keyboard_key::f14, "f14" },
        { keyboard_key::f15, "f15" },
        { keyboard_key::pause, "pause" }
    };

    std::string unknown_keyboard_key = "unknown";

}

gorc::keyboard_key gorc::string_to_keyboard_key(std::string const &s)
{
    auto it = string_to_keyboard_key_map.find(s);
    if(it != string_to_keyboard_key_map.end()) {
        return it->second;
    }
    return keyboard_key::unknown;
}

std::string const &gorc::keyboard_key_to_string(keyboard_key k)
{
    auto it = keyboard_key_to_string_map.find(k);
    if(it != keyboard_key_to_string_map.end()) {
        return it->second;
    }
    return unknown_keyboard_key;
}

gorc::keyboard::~keyboard()
{
    return;
}
