NAME:=base

DEPENDENCIES:= \
	libs/utility \
	libs/math \
	libs/program \
	libs/io \
	libs/text \

SOURCES:= \
	application_presenter.cpp \
	content/asset.cpp \
	content/assets/font.cpp \
	content/assets/shader.cpp \
	content/assets/shader_program.cpp \
	content/assets/sound.cpp \
	content/assets/texture.cpp \
	content/content_manager.cpp \
	content/json_loader.cpp \
	content/loader.cpp \
	libold/base/content/loaders/shader_loader.cpp \
	libold/base/content/loaders/shader_program_loader.cpp \
	libold/base/content/loaders/sound_loader.cpp \
	content/text_loader.cpp \
	diagnostics/error.cpp \
	diagnostics/error_level.cpp \
	diagnostics/error_location.cpp \
	events/destroyed.cpp \
	events/exit.cpp \
	events/exiting.cpp \
	events/print.cpp \
	events/resized.cpp \
	events/terminated.cpp \
	events/window_focus.cpp \
	graphics/default_render_target.cpp \
	graphics/depth_render_target.cpp \
	graphics/gui_renderer.cpp \
	graphics/render_target.cpp \
	graphics/texture_render_target.cpp \
	gui/gui_view.cpp \
	gui/widget.cpp \
	gui/widgets/button.cpp \
	gui/widgets/check_box.cpp \
	gui/widgets/dialog_box.cpp \
	gui/widgets/dynamic_image.cpp \
	gui/widgets/edit_box.cpp \
	gui/widgets/file_open_box.cpp \
	gui/widgets/frame.cpp \
	gui/widgets/grid_panel.cpp \
	gui/widgets/horizontal_split_panel.cpp \
	gui/widgets/input_block_panel.cpp \
	gui/widgets/menu_bar.cpp \
	gui/widgets/message_box.cpp \
	gui/widgets/panel.cpp \
	gui/widgets/popup_menu.cpp \
	gui/widgets/radio_button.cpp \
	gui/widgets/static_image.cpp \
	gui/widgets/static_text.cpp \
	gui/widgets/vertical_split_panel.cpp \
	gui/widgets/wrapped_text.cpp \
	input/input_adapter.cpp \
	place/presenter.cpp \
	text/location.cpp \
	text/source.cpp \
	text/token.cpp \
	text/tokenizer.cpp \
	utility/aspect.cpp \
	utility/component_system.cpp \
	utility/entity_id.cpp \
	utility/fourcc.cpp \
	utility/game_loop.cpp \
	utility/presenter.cpp \
	utility/randomizer.cpp \
	utility/time.cpp \
	utility/time_span.cpp \
	utility/timestamp.cpp \
	utility/timestamp_factory.cpp \
	view.cpp \
